In [1]:
# Import essential libraries
import pandas as pd
import numpy as np

# Load the dataset using your file path
df = pd.read_csv(r"C:\Users\Dell\OneDrive\Documents\Projects\Netflix_Content_Analysis\data\raw\netflix_titles.csv")

# Display first 5 rows
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
# Shape of dataset (rows, columns)
print("Dataset Shape:", df.shape)

# Column names
print("\nColumn Names:")
print(df.columns)
print(df.columns.tolist())

# Data types and null info
print("\nData Info:")
df.info()

Dataset Shape: (8807, 12)

Column Names:
Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')
['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [3]:
# Check for null values in each column
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [4]:
# Check duplicate records
duplicates = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicates}")

Number of duplicate rows: 0

In [5]:
# Quick statistical summary (only for numeric columns)
df.describe(include='all').T.head(10)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
show_id,8807,8807,s1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type,8807,2,Movie,6131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,8807,8807,Dick Johnson Is Dead,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
director,6173,4528,Rajiv Chilaka,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cast,7982,7692,David Attenborough,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,7976,748,United States,2818,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_added,8797,1767,"January 1, 2020",109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_year,8807.0,NaN,NaN,NaN,2014.180198,8.819312,1925.0,2013.0,2017.0,2019.0,2021.0
rating,8803,17,TV-MA,3207,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration,8804,220,1 Season,1793,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# View random 5 records
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5883,s5884,Movie,Naomi and Ely's No Kiss List,Kristin Hanggi,"Victoria Justice, Pierson Fode, Matthew Daddar...",United States,"November 18, 2015",2015,TV-MA,91 min,"Comedies, Dramas, LGBTQ Movies","Naomi and her gay best friend, Ely, have been ..."
4497,s4498,Movie,Oddbods: Party Monsters,NaN,"Nadia Ramlee, Chio Su-Ping, Jeremy Linn, Marlo...",NaN,"October 19, 2018",2018,TV-Y,23 min,Movies,"Dressed up as detective Sherlock Holmes, Slick..."
3347,s3348,Movie,The King,David Michôd,"Timothée Chalamet, Joel Edgerton, Robert Patti...","United Kingdom, Hungary, Australia","November 1, 2019",2019,R,141 min,Dramas,Wayward Prince Hal must turn from carouser to ...
7480,s7481,TV Show,Momo Salon,NaN,"Lizzy, Jung-min Park, Sang-hee Lee",South Korea,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",An aspiring hair stylist opens her own salon. ...
8019,s8020,Movie,Silicon Cowboys,Jason Cohen,NaN,United States,"April 1, 2017",2016,TV-PG,77 min,Documentaries,This documentary tells the story of Compaq Com...